from PyQt5 import QtWidgets, QtCore, QtGui

class MojWid(QtWidgets.QWidget):
        def __init__(self):
                super().__init__()
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                self.CpuWidget = QtWidgets.QWidget()
                self.CpuWidget.setPalette(palette)
                self.CpuWidget.setAutoFillBackground(True)
                self.CpuWidget.setObjectName("CpuWidget")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CpuWidget)
                self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setSpacing(1)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.label_2 = QtWidgets.QLabel(self.CpuWidget)
                self.label_2.setMinimumHeight(25)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_2.setFont(font)
                self.label_2.setObjectName("label_2")
                self.horizontalLayout_2.addWidget(self.label_2)
                self.label_3 = QtWidgets.QLabel(self.CpuWidget)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.horizontalLayout_2.addWidget(self.label_3)
                self.textBrowser = QtWidgets.QLabel(self.CpuWidget)
                self.textBrowser.setEnabled(True)
                self.textBrowser.setObjectName("textBrowser")
                self.horizontalLayout_2.addWidget(self.textBrowser)
                self.label_4 = QtWidgets.QLabel(self.CpuWidget)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.horizontalLayout_2.addWidget(self.label_4)
                self.textBrowser_2 = QtWidgets.QLabel(self.CpuWidget)
                self.textBrowser_2.setObjectName("textBrowser_2")
                self.horizontalLayout_2.addWidget(self.textBrowser_2)
                _translate = QtCore.QCoreApplication.translate
                self.label_2.setText(_translate("Form", "CPU 0:"))
                self.label_3.setText(_translate("Form", "Frequency: "))
                self.label_4.setText(_translate("Form", "Temp: "))
                self.frame = QtWidgets.QFrame(self)
                self.frame.setFrameShape(QtWidgets.QFrame.Box)
                self.frame.setMinimumSize(322,0)
                self.frame.setMaximumHeight(20)
                self.frame.move(0,3)
                self.frame.setAutoFillBackground(True)
                self.frame.setPalette(palette)
                self.setLayout(self.horizontalLayout_2)
        
        
